### PR TITLE
Bump Kubernetes dependencies (#215)

### PR DESCRIPTION
**Pull request by ybettan**
Move to the new sets.Set type as sets.String is now deprecated. Bump mockgen to a version that supports generics.
Bump golangci-lint.

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Signed-off-by: Yoni Bettan <yonibettan@gmail.com>

---

Fixes https://github.com/rh-ecosystem-edge/kernel-module-management/issues/389

### CODE REVIEW

**Comment by qbarrand** [comment]
/hold
@ybettan OCP 4.12 uses Kubernetes 1.25, we should not upgrade those deps.

**Comment by ybettan** [comment]
@qbarrand Indeed but I wanted to check if it passes CI and it does. Seems like a newer client still work with older clusters.
Do you still think we shouldn't update the API version?

**Comment by qbarrand** [comment]
> Seems like a newer client still work with older clusters.

Some features might break. I do not see the benefit tbh.

**Pull request closed without merging**
