### PR TITLE
ci: Enable Netlify builds for the documents part of the repo

### PR DESCRIPTION
**Pull request by iranzo**
Similar to upstream, add relevant files to get netlify being able to build the docs site

example render at: https://kmmrh.iranzo.io/

Note: this one has the cherry-pick of the upstream commit + the missing files in the repo

Signed-off-by: Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>

### CODE REVIEW

**Comment by qbarrand** [comment]
@iranzo OK to close this in favor of the product docs?

**Comment by iranzo** [comment]
> @iranzo OK to close this in favor of the product docs?

It's fine, but this one came in to keep both in sync, but adding also the missing pieces here to have both at the same level.

Additionally, there will be files like labs, etc that are here and not in the upstream one, but we might want to add info there so that users can test or prepare labs to practice with the technology

**Comment by qbarrand** [comment]
Cherry-picked into #379. Thanks @iranzo!

**Pull request closed without merging**
