### PR TITLE
Removing `gcr.io/kubebuilder/kube-rbac-proxy` from the `kustomize` manifests.

### PR DESCRIPTION
**Pull request by ybettan**
This image replacement is not used anymore.

---

/assign @yevgeny-shnaidman @TomerNewman

### CODE REVIEW

**Comment by ybettan** [comment]
Fixes https://github.com/rh-ecosystem-edge/kernel-module-management/issues/1275

**Comment by TomerNewman** [comment]
/approve from my end
Lets wait for @yevgeny-shnaidman to lgtm this jsut to make sure :)

**Comment by ybettan** [comment]
Fixes https://github.com/rh-ecosystem-edge/kernel-module-management/issues/1275

**Pull request merged**
