### PR TITLE
Consuming the official kernel-module-management-signimage.

### PR DESCRIPTION
**Pull request by ybettan**
Signed-off-by: Yoni Bettan <yonibettan@gmail.com>

### CODE REVIEW

**Comment by ybettan** [comment]
/cc @qbarrand
/hold
Should only be merged after https://github.com/openshift/release/pull/34914

**Review by qbarrand — APPROVED** [review]

**Comment by ybettan** [comment]
At a later point, we should be able to parameterize that image to a customer image via an env variable.

**Comment by ybettan** [comment]
/hold
Image still doesn't exist.

**Review by qbarrand — APPROVED** [review]

**Comment by ybettan** [comment]
/unhold
Image exists https://quay.io/repository/edge-infrastructure/kernel-module-management-signimage?tab=tags

**Pull request merged**
