### PR TITLE
Set EnvironmentFile=/etc/mco/proxy.env in the systemd services

### PR DESCRIPTION
**Pull request by borball**
Set EnvironmentFile=/etc/mco/proxy.env in the systemd services so that the script will respect the proxy settings on the cluster.

### CODE REVIEW

**Comment by yevgeny-shnaidman** [comment]
why is it needed?

**Comment by borball** [comment]
@yevgeny-shnaidman on a cluster which has proxy enabled we need that file to enable the proxy so that the scripts can fetch the images, otherwise the image pulling will be failed.

**Comment by yevgeny-shnaidman** [comment]
> @yevgeny-shnaidman on a cluster which has proxy enabled we need that file to enable the proxy so that the scripts can fetch the images, otherwise the image pulling will be failed.

Ok, i see, thank you for explanation! I am ok with the PR, please just fix the unit-tests, and we can push it

**Comment by ybettan** [comment]
/retest
@borball Thank you for your PR.
Please rebase and squash your PR into a single commit with a descriptive commit message that describe why it is needed.

We have a [CI job](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/rh-ecosystem-edge_kernel-module-management/1168/pull-ci-rh-ecosystem-edge-kernel-module-management-main-check-commits-count/1826788073334116352) enforcing a single commit per PR to prevent merging PRs with commit messages like `fix unit test`:

**Comment by borball** [comment]
@ybettan Thanks, I fixed the commit message.

**Pull request merged**
